# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-02-27 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, help_text='Si se quiere auto-generar otro slug, dejarlo en blanco.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'ordering': ('title',),
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, help_text='Si se quiere auto-generar otro slug, dejarlo en blanco.', max_length=255, unique=True)),
                ('code', models.CharField(help_text='https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes', max_length=10, unique=True, verbose_name='Código')),
                ('flag', models.ImageField(upload_to='resources/languages', verbose_name='Bandera')),
            ],
            options={
                'verbose_name': 'Idioma',
                'ordering': ('title',),
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='QuickResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, help_text='Si se quiere auto-generar otro slug, dejarlo en blanco.', max_length=255, unique=True)),
                ('link', models.URLField(verbose_name='Enlace')),
                ('message', models.TextField(blank=True, default='', help_text='Añade cualquier sugerencia', verbose_name='Mensaje')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_resource_owner', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Recurso rápido',
                'ordering': ('-create_at',),
                'verbose_name_plural': 'Recursos rápidos',
            },
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Puntuación')),
            ],
            options={
                'verbose_name': 'Ratio',
                'verbose_name_plural': 'Ratios',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, help_text='Si se quiere auto-generar otro slug, dejarlo en blanco.', max_length=255, unique=True)),
                ('link', models.URLField(verbose_name='Enlace')),
                ('image', models.ImageField(blank=True, default='', upload_to='resources/resources', verbose_name='Imagen')),
                ('description', models.TextField(help_text='<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet"target="_blank">Markdown</a> permitido', verbose_name='Descripcción')),
                ('views', models.IntegerField(default=0, verbose_name='Visitas')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks enlace')),
                ('marked_broken', models.PositiveIntegerField(blank=True, default=0, verbose_name='Marcados como rotos')),
                ('marked_spam', models.PositiveIntegerField(blank=True, default=0, verbose_name='Marcados como spam')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha publicación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('categories', models.ManyToManyField(related_name='resource_categories', to='resources.Category', verbose_name='Categorías')),
                ('languages', models.ManyToManyField(related_name='resource_languages', to='resources.Language', verbose_name='Idiomas')),
            ],
            options={
                'verbose_name': 'Recurso',
                'ordering': ('-create_at',),
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titulo')),
                ('slug', models.SlugField(blank=True, help_text='Si se quiere auto-generar otro slug, dejarlo en blanco.', max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='resources/tags', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'ordering': ('title',),
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='main_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_main_tag', to='resources.Tag', verbose_name='Etiqueta principal'),
        ),
        migrations.AddField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_owner', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(related_name='resource_tags', to='resources.Tag', verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='ratio',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratio_resource', to='resources.Resource', verbose_name='Recursos'),
        ),
        migrations.AddField(
            model_name='ratio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratio_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='ratio',
            unique_together=set([('user', 'resource')]),
        ),
    ]
