# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-01 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('-code',), 'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.ImageField(help_text='Si son mas de 3 idiomas, selecciona Multi Lenguaje', upload_to='resources/languages', verbose_name='Bandera'),
        ),
    ]
