# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-01 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20170301_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.ImageField(upload_to='resources/languages', verbose_name='Bandera'),
        ),
    ]
