# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='resources/categories', verbose_name='Imagen'),
        ),
    ]
