# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20170302_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Formato')),
                ('image', models.ImageField(upload_to='resources/formats', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Formato',
                'ordering': ('title',),
                'verbose_name_plural': 'Formatos',
            },
        ),
    ]
