# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_resource_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_format', to='resources.ResourceFormat', verbose_name='Formato'),
        ),
    ]
