# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20170303_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='require_register',
            field=models.BooleanField(default=False, verbose_name='Requiere registro'),
        ),
    ]
